# -*- shell-script -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Update the shell to the current setup.
alias upenv="exec zsh"
# Workaround to make this work with tmux.
alias terminal-notifier='reattach-to-user-namespace terminal-notifier'
tn() {
    echo "$@"| terminal-notifier
}

# Mkdir and cd into it
mkdircd ()
{
    mkdir -p -- "$1" &&
        cd -P -- "$1"
}
alias mc="mkdircd"

# Get the current datetime as a UTC ISO str
utc () {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Get the cheat.sh docs for the given command
cheat () {
    curl cheat.sh/"$1"
}
alias ch="cheat"

# Emacs
# When emacs is frozen, run this to force Emacs to stop what it's doing and give control back to you.
# One side-effect of this is that debug-on-quit is toggled, so we toggle it off immediately afterward
unfreeze-emacs() {
    # On OSX, emacs is known as `Emacs`
    pkill -SIGUSR2 Emacs

    # Undo `debug-on-quit`
    emacsclient --eval "(progn (toggle-debug-on-quit))"
}

# Output the biggest 10 files in human readable form.
big-files() {
    # Uses gsort installed from `brew install coreutils`
    du -hsx * | gsort -rh | head -10
}

# Install git-subrepo.
source ~/.dotfiles/git-subrepo/.rc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
